name: 1 - hello - world

on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print hello
              run: echo "Hello World"

            - name: Print Goodbye
              run: echo "GoodBye"

    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hi to you
              run: echo "Hi to you"

            - name: I will fail
              run: exit 0

            - name: Say GoodBye
              run: echo "GoodBye"

              
