name: 2 - different inputs

#on: workflow_dispatch

on: 
    push:
        #schedule:
            #- cron: "*/5 * * * *"
    workflow_dispatch:
        inputs:
            MySQL:
                required: false
                type: boolean
            PostgreSQL:
                required: false
                type: boolean

jobs:
    fetch-data:
        runs-on: ubuntu-latest
        steps:
            - name: MySQL fetch
              if: ${{ github.event.inputs.MySQL == 'true'}}
              run: echo "I Will Retrieve Data from MySQL"

            - name: PostgreSQL fetch
              if: ${{ github.event.inputs.PostgreSQL == 'true'}}
              run: echo "I Will Retrieve Data from PostgreSQL"
              
            - name: Done
              run: echo "You Did it"
